function createfigure(XData1, YData1, XData2, YData2, XData3, YData3, X1, Y1, xdata4, zdata1, cdata1)
%CREATEFIGURE(XDATA1, YDATA1, XDATA2, YDATA2, XDATA3, YDATA3, X1, Y1, XDATA4, ZDATA1, CDATA1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  X1:  vector of x data
%  Y1:  vector of y data
%  XDATA4:  surface xdata
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 21-Feb-2016 19:40:55

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1,...
    'PlotBoxAspectRatio',[187.409090909091 143.288372093023 143.288372093023],...
    'DataAspectRatio',[1 1 1]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[-1.43827428980079 1.4387777474176]);
box(subplot1,'on');

% Create line
line(XData1,YData1,'Parent',subplot1,'MarkerSize',8,'Marker','o',...
    'LineWidth',1,...
    'LineStyle','none');

% Create line
line(XData2,YData2,'Parent',subplot1,'MarkerSize',8,'Marker','x',...
    'LineWidth',1,...
    'LineStyle','none');

% Create line
line(XData3,YData3,'Parent',subplot1,'HitTest','off','LineStyle',':');

% Create xlabel
xlabel('Real Part');

% Create ylabel
ylabel('Imaginary Part');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.775 0.341162790697674]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2);

% Create xlabel
xlabel('Normalised Frequency (x\pi rads/sample)');

% Create ylabel
ylabel('Magnitude (db) ');

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1,...
    'YTickLabel',['-1.5';'-0.5';'0.5 ';'1.5 '],...
    'YTick',[-1.5 -0.5 0.5 1.5],...
    'XTickLabel',['-1.5';'-0.5';'0.5 ';'1.5 '],...
    'XTick',[-1.5 -0.5 0.5 1.5],...
    'CameraUpVector',[-0.1237 0.5153 23.1286],...
    'CameraPosition',[3.7719 -15.7111 275.3541]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[-1.1 1.1]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-1.1 1.1]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot2,[-30 30]);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'on');

% Create mesh
mesh(xdata4,xdata4,zdata1,cdata1,'Parent',subplot2);

% Create xlabel
xlabel('Re');

% Create ylabel
ylabel('Im');

% Create zlabel
zlabel('Mag(db)');

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

